name: PokemonPlugin
version: 1.0.0
main: com.icetea520.pokemon.PokemonPlugin
api-version: 1.20
author: IceTea_520
description: Minecraft 寶可夢插件

commands:
  pokemon:
    description: 寶可夢插件主指令
    usage: /pokemon <子指令>
    aliases: [pk, pokemon]

permissions:
  pokemon.*:
    description: 允許使用所有寶可夢功能
    default: true
  pokemon.mode:
    description: 允許切換模式
    default: true
  pokemon.bag:
    description: 允許使用捕捉背包
    default: true
  pokemon.catch:
    description: 允許使用捕捉球
    default: true
  pokemon.get:
    description: 允許獲取物品 (僅 OP)
    default: op
